[server]
url = "http://era.islab.di.unimi.it/"
user = "admin"
password = "admin1234"

# ENTITY TYPE MAPPING AND PROPERTIES DEFINITION

[mapping]
"ID" = "source"
"Family" = "group"
"Typology" = "group"
"Name (as marked in document(s))" = "appellation"
"Subcomponents (IDs)" = "object"
"Part of (IDs)" = "object"
"Material(s)" = "material"
"External resources" = "object"

[properties.ID] 
"Description" = "text" 

[delimited_fields]
"Subcomponents (IDs)" = ";"
"Part of (IDs)" = ";"
"Material(s)" = ";"


# RELATIONS DEFINITION

[[relations]]
name = "has_group"
entity1 = "ID" 
entity2 = "Family" 

[[relations]]
name = "has_group"
entity1 = "ID" 
entity2 = "Typology" 

[[relations]]
name = "has_appellation"
entity1 = "ID" 
entity2 = "Name (as marked in document(s))" 

[[relations]]
name = "has_subcomponent"
entity1 = "ID" 
entity2 = "Subcomponents (IDs)" 

[[relations]]
name = "part_of"
entity1 = "ID" 
entity2 = "Part of (IDs)" 

[[relations]]
name = "made_of"
entity1 = "ID" 
entity2 = "Material(s)"

[[relations]]
name = "has_external_resource"
entity1 = "ID" 
entity2 = "External resources"